AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-typescript-api

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        STAGE: dev

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${env}-${AWS::StackName}-getAllItemsFunction"
      CodeUri: src/handlers/
      Handler: get-all-items.getAllItemsHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.      
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  # getByIdFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: !Sub "${env}-${AWS::StackName}-getByIdFunction"
  #     CodeUri: src/handlers/
  #     Handler: get-by-id.getByIdHandler
  #     Runtime: nodejs12.x
  #     MemorySize: 128
  #     Timeout: 100
  #     Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
  #     Events:
  #       Api:
  #         Type: Api
  #         Properties:
  #           Path: /{id}
  #           Method: GET

  # putItemFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: !Sub "${env}-${AWS::StackName}-putItemFunction"
  #     CodeUri: src/handlers/
  #     Handler: put-item.putItemHandler
  #     Runtime: nodejs12.x
  #     MemorySize: 128
  #     Timeout: 100
  #     Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.      
  #     Events:
  #       Api:
  #         Type: Api
  #         Properties:
  #           Path: /
  #           Method: POST
  

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"